name: Build to test PR

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build binary
        run: cargo build --release
      - name: Create tarball
        run: |
          mv target/release/yt-transcriber yt-transcriber
          tar -czf yt-transcriber-linux-x86_64.tar.gz yt-transcriber
      - name: Generate checksum
        run: sha256sum yt-transcriber-linux-x86_64.tar.gz > yt-transcriber-linux-x86_64.sha256
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: yt-transcriber-linux-x86_64
          path: |
            yt-transcriber-linux-x86_64.tar.gz
            yt-transcriber-linux-x86_64.sha256
